language: objective-c
before_install:
    - sudo easy_install cpp-coveralls

before_script:
    - cd ISO8601ForCocoa
script:
    - xcodebuild test -scheme 'ISO8601ForCocoa' SRCROOT=../build OBJROOT=../build SHARED_PRECOMPS_DIR=../build
    - xcodebuild -arch i386 -target ISO8601ForCocoaTouchTests -configuration Debug -sdk iphonesimulator6.1 SRCROOT=../build OBJROOT=../build SHARED_PRECOMPS_DIR=../build ONLY_ACTIVE_ARCH=NO TEST_AFTER_BUILD=YES clean build
after_success:
    - cd ..
    - coveralls -x '.m'
